on:
  push:
    branches:
      - main
  pull_request:

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          release-type: python
          package-name: snakemake-storage-plugin-xrootd

  build-distributions:
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3

      - name: Build distributions
        run: git fetch --tags && pixi exec python-build

      - name: Check package metadata
        run: pixi exec twine check dist/*

      - name: Publish package on PyPI
        if: needs.release-please.outputs.release_created
        uses: pypa/gh-action-pypi-publish@release/v1
